# Generated by Django 3.1.6 on 2021-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210227_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='some_var',
        ),
        migrations.AddField(
            model_name='appointments',
            name='Address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointments',
            name='City',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointments',
            name='Country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointments',
            name='Flatno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointments',
            name='State',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointments',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='appointments',
            name='age',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='contact',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='appointments',
            name='covid_status',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=30),
        ),
        migrations.AddField(
            model_name='appointments',
            name='current_symptom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointments',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=30),
        ),
        migrations.AddField(
            model_name='appointments',
            name='medical_issues',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
