# Generated by Django 3.1.6 on 2021-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210227_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='aadhar',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='current_symptom',
            field=models.CharField(blank=True, default='N.A.', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='medical_issues',
            field=models.CharField(default='N.A.', max_length=100),
        ),
    ]
