# Generated by Django 3.1.6 on 2021-02-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210227_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='aadhar',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='contact',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
