# Generated by Django 3.1.6 on 2021-02-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210227_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('aadhar', models.CharField(blank=True, max_length=16)),
                ('contact', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('Flatno', models.CharField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=50)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('State', models.CharField(blank=True, max_length=50)),
                ('Country', models.CharField(blank=True, max_length=50)),
                ('medical_issues', models.CharField(default='N.A.', max_length=100)),
                ('current_symptom', models.CharField(blank=True, default='N.A.', max_length=50)),
                ('covid_status', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=30)),
                ('desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
