# Generated by Django 3.1.6 on 2021-02-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210228_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='image',
            field=models.ImageField(default='default.png', upload_to='appointment_verification'),
        ),
    ]
