# Generated by Django 3.1.6 on 2021-02-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_appointment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='covid_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
