# Generated by Django 3.1.6 on 2021-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210228_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='travel_history',
            field=models.CharField(default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='covid_status',
            field=models.CharField(default='Negative', max_length=30),
        ),
    ]
