# Generated by Django 3.1.6 on 2021-02-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210228_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dose',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
