# Generated by Django 3.1.6 on 2021-02-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210228_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='center',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
