# Generated by Django 3.1.6 on 2021-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidences',
            name='slots_available',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='incidences',
            name='vaccine_available',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
