# Generated by Django 3.1.6 on 2021-02-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20210227_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidences',
            name='slots_available',
        ),
        migrations.RemoveField(
            model_name='incidences',
            name='vaccine_available',
        ),
        migrations.AddField(
            model_name='incidences',
            name='five',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='incidences',
            name='four',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='incidences',
            name='one',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='incidences',
            name='three',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='incidences',
            name='today',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='incidences',
            name='two',
            field=models.IntegerField(default=30),
        ),
    ]
