# Generated by Django 3.1.6 on 2021-02-28 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20210227_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='five',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='incidences',
            name='four',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='incidences',
            name='ones',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='incidences',
            name='three',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='incidences',
            name='todays',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='incidences',
            name='two',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
